server:
  port: 8081
  error:
    include-message: always
logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ngs-website
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate.jdbc.time_zone: UTC
        hibernate.generate_statistics: false
        hibernate.format_sql: true
      open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    jpa:
      repositories:
        enabled: true
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://172.16.15.11:3308/}${DATABASE_NAME:ngs_website}?createDatabaseIfNotExist=true
    #    url: ${DATABASE_URL:jdbc:mysql://171.244.51.190:3308/}${DATABASE_NAME:vna_user}?createDatabaseIfNotExist=true
    #    url: ${DATABASE_URL:jdbc:mysql://172.16.15.11:3308/}${DATABASE_NAME:vna_user}?createDatabaseIfNotExist=true
    username: root
    password: ROOTPWD